#Episode 39
#   Naam:
#    Permission: "alonsotscplugin.vip+"
#    Name: "VIP+" In discord

Role-sync:
  Eigenaar:
    Permission: "wantednetwork.eigenaar"
    Name: "Eigenaar"
  Manager:
    Permission: "wantednetwork.manager"
    Name: "Manager"
  SyrAdmin:
    Permission: "wantednetwork.syradmin"
    Name: "Syr. Admin"
  Admin:
    Permission: "wantednetwork.admin"
    Name: "Admin"
  Moderator:
    Permission: "wantednetwork.moderator"
    Name: "Moderator"
  Helper:
    Permission: "wantednetwork.helper"
    Name: "Helper"
  Emerald:
    Permission: "wantednetwork.emerald"
    Name: "Emerald"
  Diamond:
    Permission: "wantednetwork.diamond"
    Name: "Diamond"
  Gold:
    Permission: "wantednetwork.gold"
    Name: "Gold"
  Iron:
    Permission: "wantednetwork.iron"
    Name: "Iron"
  Koning:
    Permission: "wantednetwork.koning"
    Name: "Koning(in)"